Algoritmo "sessenta_porcento"
// Descrição   : 60% de um número inteiro
// Autor(a)    : Luiz Augusto
// Data atual  : 07/08/2024
Var
// Seção de Declarações das variáveis 
   n: inteiro
   p: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite um número: ")
   leia(n)
   p <- n * 0.6
   escreva("60% de", n, " é igual:", p)
   

Fimalgoritmo