Algoritmo "subtracao"
// Descrição   : Subtração de dois números inteiros
// Autor(a)    : Luiz Augusto
// Data atual  : 07/08/2024
Var
// Seção de Declarações das variáveis 
   a, b, s: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o primeiro número: ")
   leia(a)
   escreva("Digite o segundo número: ")
   leia(b)
   s <- a - b
   escreva("A subtração de", a, " e", b, " é igual:", s)

Fimalgoritmo