Algoritmo "media"
// Descrição   : Média de dois números
// Autor(a)    : Luiz Augusto
// Data atual  : 07/08/2024
Var
// Seção de Declarações das variáveis 
   a, b: inteiro
   m: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite o primeiro número: ")
   leia(a)
   escreva("Digite o segundo número: ")
   leia(b)
   m <- (a+b)/2
   escreva("A média de", a, " mais", b, " é igual:", m)
   
Fimalgoritmo