Algoritmo "soma"
// Descrição   : Somador de dois números inteiros
// Autor(a)    : Luiz Augusto
// Data atual  : 07/08/2024
Var
// Seção de Declarações das variáveis 
   a, b, s: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite dois números: ")
   leia(a, b)
   s <- a+b
   escreva("A soma de", a, " mais", b, " é igual:", s)
   
Fimalgoritmo