Algoritmo "palavras_concatenadas"
// Descrição   : Concatena duas palavras em uma terceira
// Autor(a)    : Luiz Augusto
// Data atual  : 21/09/2024
Var
// Seção de Declarações das variáveis 
   palavra1, palavra2 : caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite a primeira palavra: ")
   leia(palavra1)
   escreva("Digite a segunda palavra: ")
   leia(palavra2)
   
   escreva(palavra1 + palavra2)

Fimalgoritmo