Algoritmo "quatro_primeiros_caracteres"
// Descrição   : Retorna os quatro primeiros caracteres
// Autor(a)    : Luiz Augusto
// Data atual  : 21/09/2024
Var
// Seção de Declarações das variáveis 
   palavra : caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite uma palavra: ")
   leia(palavra)
   
   escreva(copia(palavra, 1, 4))

Fimalgoritmo