Algoritmo "tres_caracteres_apos_segundo"
// Descrição   : Retorna três caracteres após o segundo
// Autor(a)    : Luiz Augusto
// Data atual  : 21/09/2024
Var
// Seção de Declarações das variáveis 
   palavra : caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite uma palavra: ")
   leia(palavra)
   
   escreva(copia(palavra, 3, 3))

Fimalgoritmo